import { Suspense } from "react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { DailyNarrativeUI } from "./daily-narrative-ui";

// ── Types ─────────────────────────────────────────────────────────────────────

export type ArticleSource = {
  article_id: number;
  title: string;
  url: string;
  published_at?: string | null;
};

export type PortfolioWatchItem = {
  ticker: string;
  sentiment: number;
  narrative: string;
  action: "monitor" | "review" | "urgent";
  sources?: ArticleSource[];
};

export type ScreeningUpdateItem = {
  ticker: string;
  narrative: string;
  sources?: ArticleSource[];
};

export type AlertWatchItem = {
  ticker: string;
  alert_type: "stop_loss" | "take_profit" | "price_alert";
  alert_price: number;
  pct_away: number | null;
  narrative: string;
  sources?: ArticleSource[];
};

export type DailyNarrativeRow = {
  id: string;
  narrative_date: string;
  portfolio_section: PortfolioWatchItem[] | null;
  screening_section: ScreeningUpdateItem[] | null;
  alert_warnings: AlertWatchItem[] | null;
  market_pulse: string | null;
  market_pulse_sources?: ArticleSource[] | null;
  model: string | null;
  latency_ms: number | null;
  generated_at: string;
};

// ── Data fetcher ──────────────────────────────────────────────────────────────

async function NarrativeData() {
  const supabase = await createClient();
  const { data: claims, error: claimsError } = await supabase.auth.getClaims();

  if (claimsError || !claims?.claims) {
    redirect("/auth/login");
  }

  // Fetch the last 7 narratives (most recent first)
  const { data: rows, error } = await supabase
    .schema("swingtrader")
    .from("daily_narratives")
    .select(
      "id, narrative_date, portfolio_section, screening_section, alert_warnings, market_pulse, market_pulse_sources, model, latency_ms, generated_at"
    )
    .order("narrative_date", { ascending: false })
    .limit(7);

  if (error) {
    return (
      <div className="rounded-lg border border-border bg-card p-6 text-sm text-muted-foreground">
        <p className="font-medium text-foreground">Could not load narratives</p>
        <p className="mt-1">{error.message}</p>
        <p className="mt-2 text-xs">
          Make sure the migration{" "}
          <code className="rounded bg-muted px-1 py-0.5 font-mono text-[11px]">
            20260412200000_daily_narrative.sql
          </code>{" "}
          has been applied.
        </p>
      </div>
    );
  }

  return <DailyNarrativeUI narratives={(rows ?? []) as DailyNarrativeRow[]} />;
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function DailyNarrativePage() {
  return (
    <div className="flex-1 w-full flex flex-col gap-6">
      <div>
        <p className="text-xs font-semibold uppercase tracking-widest text-amber-500">Intelligence</p>
        <h1 className="mt-1 text-2xl font-bold tracking-tight">The Daily Narrative</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Pre-market briefing — what&apos;s happening with your portfolio and screening candidates.
          Generated by Ollama each morning from the last 24h of scored news.
        </p>
      </div>

      <Suspense
        fallback={
          <div className="text-sm text-muted-foreground animate-pulse rounded-lg border border-border p-6">
            Loading narrative…
          </div>
        }
      >
        <NarrativeData />
      </Suspense>
    </div>
  );
}
