/**
 * Render the Supabase Auth email templates to files for pasting into the
 * dashboard (Authentication → Emails → Templates).
 *
 * Nothing here talks to Supabase or Resend — the dashboard is the only place
 * these templates live at runtime, so this just writes HTML and prints the
 * settings that have to match.
 *
 *   npx tsx scripts/build-supabase-auth-emails.ts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { buildAuthEmails } from "../emails/supabase-auth";

const OUT_DIR = join(process.cwd(), "output", "supabase-auth");

function main() {
  const templates = buildAuthEmails();
  mkdirSync(OUT_DIR, { recursive: true });

  for (const t of templates) {
    writeFileSync(join(OUT_DIR, `${t.slug}.html`), t.html, "utf8");
  }

  const readme = [
    "# Supabase Auth email templates",
    "",
    "Generated by `scripts/build-supabase-auth-emails.ts`. Do not edit these files —",
    "edit `emails/supabase-auth.ts` and rebuild, or the next run overwrites you.",
    "",
    "Paste each into Supabase → Authentication → Emails → Templates, setting both",
    "the Subject and the Message body.",
    "",
    "| File | Dashboard template | Subject |",
    "| ---- | ------------------ | ------- |",
    ...templates.map((t) => `| \`${t.slug}.html\` | ${t.dashboardName} | ${t.subject} |`),
    "",
    "## Settings these templates assume",
    "",
    "- **Site URL** (Authentication → URL Configuration) must be the public origin,",
    "  e.g. `https://newsimpactscreener.com`. Every link is built from `{{ .SiteURL }}`,",
    "  so a wrong value here breaks all of them at once.",
    "- **Redirect URLs** must allow `https://newsimpactscreener.com/**`.",
    "- **Email OTP Expiration** (Authentication → Providers → Email) must match the",
    "  expiry these emails state. Rebuild with `SUPABASE_OTP_EXPIRY_MINUTES=<n>` if you",
    "  change it, or the copy will lie.",
    "- **Custom SMTP** pointed at Resend, per EMAIL_SETUP.md §5.",
    "",
    "## Why not `{{ .ConfirmationURL }}`",
    "",
    "That variable points at Supabase's verify endpoint, which then bounces to the app.",
    "This app ships `app/auth/confirm/route.ts`, which reads `token_hash` + `type` and",
    "verifies the OTP itself — so the links here go straight there. The click stays on",
    "our domain, and the route can prime the subscription tier and fire the welcome",
    "email before redirecting.",
    "",
    "The `type` and `next` values differ per template and are not interchangeable; see",
    "the header comment in `emails/supabase-auth.ts`.",
    "",
  ].join("\n");
  writeFileSync(join(OUT_DIR, "README.md"), readme, "utf8");

  console.log(`Wrote ${templates.length} templates to ${OUT_DIR}\n`);
  for (const t of templates) {
    console.log(`  ${t.slug.padEnd(18)} → ${t.dashboardName.padEnd(22)} "${t.subject}"`);
  }
  console.log(`\n  README.md            settings + paste instructions`);
}

main();
