"""The hypothesis grammar — a finite, enumerable space of testable claims.

A hypothesis here is not free-form. It is a tuple of (signal primitive,
transform, outcome, horizon), which buys three things a free-form proposer
cannot:

  * **It can be exhausted.** The loop can report "the space is covered" rather
    than running forever, which is what makes a null terminal.
  * **It can be deduplicated.** The same claim arriving twice under different
    words would inflate the trial count while adding no information — or worse,
    be counted as an independent confirmation.
  * **It can be hashed.** The trial count that sets the significance bar is only
    meaningful if the thing being counted is well defined.

The primitives are the features this project already computes. The transforms
are the handful of ways a practitioner actually reshapes one: use it as-is,
invert it, difference it over a window, or measure it against its own recent
level. Nothing here is exotic, and that is intentional — the space is meant to
cover the plausible, not the ingenious.
"""

from __future__ import annotations

import hashlib
import itertools
from dataclasses import dataclass, field

import numpy as np

# (name, kwargs) pairs understood by FeatureBank.
SIGNAL_PRIMITIVES: dict[str, tuple[str, dict]] = {
    "rs_rank": ("rs_rank", {}),
    "mom_12_1": ("momo_12m_1m", {}),
    "residual_momentum": ("residual_momentum", {}),
    "info_discreteness": ("info_discreteness", {}),
    "pct_above_52w_low": ("pct_above_52w_low", {}),
    "pct_below_52w_high": ("pct_below_52w_high", {}),
    "rs_line_high": ("rs_line_high", {}),
    "atr_pct": ("atr_pct", {}),
    "adr_pct": ("adr_pct", {}),
    "tightness": ("tightness", {}),
    "squeeze": ("squeeze", {}),
    "gap_pct": ("gap_pct", {}),
    "volume_ratio": ("volume_ratio", {}),
    "up_down_volume": ("up_down_volume", {}),
    "dist_from_sma20": ("dist_from_sma", {"length": 20}),
    "dist_from_sma50": ("dist_from_sma", {"length": 50}),
    "dist_from_sma200": ("dist_from_sma", {"length": 200}),
    "ret_5": ("ret", {"days": 5}),
    "ret_21": ("ret", {"days": 21}),
    "ret_63": ("ret", {"days": 63}),
    "realized_vol": ("realized_vol", {"length": 20}),
    "dollar_volume_20d": ("dollar_volume_20d", {}),
}

# `negate` was in this list for the first full run and has been removed. Every
# test in the loop is TWO-SIDED, so negating a signal produces an exact sign
# mirror of the same statistic — 83 of 88 raw/negate pairs came back as exact
# mirrors. It doubled the trial count while adding no information, which inflated
# the significance bar. The direction was safe (a higher bar is harder to clear)
# but the count that sets the bar has to mean something, and a duplicate does not.
TRANSFORMS = ("raw", "delta_21", "delta_63", "vs_own_mean_63")
OUTCOMES = ("ic", "setup")
HORIZONS = (5, 21, 63)


@dataclass(frozen=True)
class Hypothesis:
    primitive: str
    transform: str
    outcome: str
    horizon: int
    note: str = ""

    @property
    def name(self) -> str:
        return f"{self.primitive}|{self.transform}|{self.outcome}|H{self.horizon}"

    @property
    def key(self) -> str:
        return hashlib.sha1(self.name.encode()).hexdigest()[:16]

    def to_dict(self) -> dict:
        return {"primitive": self.primitive, "transform": self.transform,
                "outcome": self.outcome, "horizon": self.horizon,
                "name": self.name, "key": self.key, "note": self.note}


def apply_transform(mat: np.ndarray, transform: str) -> np.ndarray:
    """Reshape a feature matrix. Every transform is backward-looking."""
    if transform == "raw":
        return mat
    if transform == "negate":
        # Retained so historical registry entries stay reproducible; no longer
        # generated by the space (see the note on TRANSFORMS).
        return -mat
    if transform.startswith("delta_"):
        k = int(transform.split("_")[1])
        prev = np.vstack([np.full((k, mat.shape[1]), np.nan), mat[:-k]])
        return mat - prev
    if transform.startswith("vs_own_mean_"):
        k = int(transform.split("_")[-1])
        import pandas as pd
        m = pd.DataFrame(mat).rolling(k, min_periods=max(5, k // 3)).mean().to_numpy()
        with np.errstate(invalid="ignore", divide="ignore"):
            return np.where(np.isfinite(m) & (np.abs(m) > 1e-12), mat / m - 1.0, np.nan)
    raise ValueError(f"unknown transform {transform!r}")


@dataclass
class HypothesisSpace:
    """The enumerable set, in a deliberate order.

    Ordering matters for an interruptible loop: `raw` and `negate` come first so
    the cheap, interpretable forms are tested before the derived ones, and a run
    stopped early has still covered the sensible part of the space rather than a
    random slice of it.
    """

    primitives: tuple = tuple(SIGNAL_PRIMITIVES)
    transforms: tuple = TRANSFORMS
    outcomes: tuple = OUTCOMES
    horizons: tuple = HORIZONS
    _order: list = field(default_factory=list)

    def all(self) -> list[Hypothesis]:
        out = []
        for tr in self.transforms:
            for oc in self.outcomes:
                for h in (self.horizons if oc == "ic" else (0,)):
                    for p in self.primitives:
                        out.append(Hypothesis(p, tr, oc, h))
        return out

    def size(self) -> int:
        return len(self.all())

    def next_untested(self, tested: set[str], n: int) -> list[Hypothesis]:
        return [h for h in self.all() if h.key not in tested][:n]
